### ISSUE TITLE
Rewrite tracking list

### ISSUE THREAD

**Issue by thinkier** [Botcoins/issue-tracker#39]
- [ ] Migration of graphing
- [ ] Think of a better fucking prefix instead of `$c`, maybe just `$`
    - [ ] `$symbol` at the start triggers the feed command with the exception of `$[numerical value]
- [ ] Feed - reduce the length even further
    - **$cp will be dropped**
- [ ] Fiat and crypto configuration will now have an order of priorities for viewing, defaulting to `("USD", "BTC")` **Interface needs to be friendlier!**
    - **Alt crypto does not default to `ETH` anymore**
- [ ] Allow scheduling of commands (limit to 3 per guild, monetize excessive use)
    - [ ] Do it in a webhook
- [ ] The calculator module will be kept
- [ ] Make Botcoins Fast Again :confounded: 
- [ ] Allow commands to be disabled 

Logical command structure
- `$[symbol].g` - graph
- `$[symbol].t` - ticker
    - `$[symbol].f` - feed (legacy name for `$[symbol].ticker`)
- `$[symbol1].$[symbol2]` - price comparison. ie. `1 symbol1 = x symbol2`
- `$#calc` - calculator function

**Comment by nadjozer** [comment]
Intervals! similar to what this bot does https://github.com/kodycode/CoinMarketBot

but improve on longer intervals (to avoid spam) and subscribe to different coins.

that will make this the most attractive chart bot in discord.

**Comment by thinkier** [comment]
That would be under "scheduling of commands" if I'm not mistaken, @nadjozer
